// Code generated by entc, DO NOT EDIT.

package like

const (
	// Label holds the string label denoting the like type in the database.
	Label = "like"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCount holds the string denoting the count field in the database.
	FieldCount = "count"
	// EdgeFeedback holds the string denoting the feedback edge name in mutations.
	EdgeFeedback = "feedback"
	// Table holds the table name of the like in the database.
	Table = "likes"
	// FeedbackTable is the table that holds the feedback relation/edge.
	FeedbackTable = "likes"
	// FeedbackInverseTable is the table name for the Feedback entity.
	// It exists in this package in order to avoid circular dependency with the "feedback" package.
	FeedbackInverseTable = "feedbacks"
	// FeedbackColumn is the table column denoting the feedback relation/edge.
	FeedbackColumn = "feedback_like"
)

// Columns holds all SQL columns for like fields.
var Columns = []string{
	FieldID,
	FieldCount,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "likes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"feedback_like",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}
