// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"recognition-wall/internal/data/ent/feedback"
	"recognition-wall/internal/data/ent/like"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// Like is the model entity for the Like schema.
type Like struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Count holds the value of the "count" field.
	Count int32 `json:"count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LikeQuery when eager-loading is set.
	Edges         LikeEdges `json:"edges"`
	feedback_like *int64
}

// LikeEdges holds the relations/edges for other nodes in the graph.
type LikeEdges struct {
	// Feedback holds the value of the feedback edge.
	Feedback *Feedback `json:"feedback,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FeedbackOrErr returns the Feedback value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LikeEdges) FeedbackOrErr() (*Feedback, error) {
	if e.loadedTypes[0] {
		if e.Feedback == nil {
			// The edge feedback was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: feedback.Label}
		}
		return e.Feedback, nil
	}
	return nil, &NotLoadedError{edge: "feedback"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Like) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case like.FieldID, like.FieldCount:
			values[i] = new(sql.NullInt64)
		case like.ForeignKeys[0]: // feedback_like
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Like", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Like fields.
func (l *Like) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case like.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			l.ID = int64(value.Int64)
		case like.FieldCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field count", values[i])
			} else if value.Valid {
				l.Count = int32(value.Int64)
			}
		case like.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field feedback_like", value)
			} else if value.Valid {
				l.feedback_like = new(int64)
				*l.feedback_like = int64(value.Int64)
			}
		}
	}
	return nil
}

// QueryFeedback queries the "feedback" edge of the Like entity.
func (l *Like) QueryFeedback() *FeedbackQuery {
	return (&LikeClient{config: l.config}).QueryFeedback(l)
}

// Update returns a builder for updating this Like.
// Note that you need to call Like.Unwrap() before calling this method if this Like
// was returned from a transaction, and the transaction was committed or rolled back.
func (l *Like) Update() *LikeUpdateOne {
	return (&LikeClient{config: l.config}).UpdateOne(l)
}

// Unwrap unwraps the Like entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (l *Like) Unwrap() *Like {
	tx, ok := l.config.driver.(*txDriver)
	if !ok {
		panic("ent: Like is not a transactional entity")
	}
	l.config.driver = tx.drv
	return l
}

// String implements the fmt.Stringer.
func (l *Like) String() string {
	var builder strings.Builder
	builder.WriteString("Like(")
	builder.WriteString(fmt.Sprintf("id=%v", l.ID))
	builder.WriteString(", count=")
	builder.WriteString(fmt.Sprintf("%v", l.Count))
	builder.WriteByte(')')
	return builder.String()
}

// Likes is a parsable slice of Like.
type Likes []*Like

func (l Likes) config(cfg config) {
	for _i := range l {
		l[_i].config = cfg
	}
}
