// Code generated by entc, DO NOT EDIT.

package ent

import (
	"recognition-wall/internal/data/ent/feedback"
	"recognition-wall/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	feedbackFields := schema.Feedback{}.Fields()
	_ = feedbackFields
	// feedbackDescCreatedAt is the schema descriptor for created_at field.
	feedbackDescCreatedAt := feedbackFields[3].Descriptor()
	// feedback.DefaultCreatedAt holds the default value on creation for the created_at field.
	feedback.DefaultCreatedAt = feedbackDescCreatedAt.Default.(func() time.Time)
	// feedbackDescUpdatedAt is the schema descriptor for updated_at field.
	feedbackDescUpdatedAt := feedbackFields[4].Descriptor()
	// feedback.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	feedback.DefaultUpdatedAt = feedbackDescUpdatedAt.Default.(func() time.Time)
}
