// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Feedback is the predicate function for feedback builders.
type Feedback func(*sql.Selector)

// Like is the predicate function for like builders.
type Like func(*sql.Selector)
