// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"recognition-wall/internal/biz"
	"recognition-wall/internal/conf"
	"recognition-wall/internal/data"
	"recognition-wall/internal/server"
	"recognition-wall/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	feedbackRepo := data.NewFeedbackRepo(dataData, logger)
	feedbackUsecase := biz.NewFeedbackUsecase(feedbackRepo, logger)
	feedbackService := service.NewFeedbackService(feedbackUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, feedbackService, logger)
	grpcServer := server.NewGRPCServer(confServer, feedbackService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
